# Generated by Django 5.1.5 on 2026-02-04 12:33

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address to monitor (e.g., dms-demo@india-alt.com)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Whether to actively monitor this email account')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last error message if sync failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'db_table': 'email_account',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['email'], name='email_accou_email_4269b0_idx'), models.Index(fields=['is_active'], name='email_accou_is_acti_507bbb_idx'), models.Index(fields=['-last_synced'], name='email_accou_last_sy_1083cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_id', models.CharField(db_index=True, help_text='Microsoft Graph API message ID', max_length=255, unique=True)),
                ('internet_message_id', models.CharField(blank=True, db_index=True, help_text='Internet Message ID (unique email identifier)', max_length=500, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Array of recipient email addresses', size=None)),
                ('cc_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Array of CC email addresses', size=None)),
                ('bcc_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Array of BCC email addresses', size=None)),
                ('body_text', models.TextField(blank=True, help_text='Plain text email body', null=True)),
                ('body_html', models.TextField(blank=True, help_text='HTML email body', null=True)),
                ('body_preview', models.TextField(blank=True, help_text='Email body preview from Graph API', null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('importance', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_read_receipt_requested', models.BooleanField(default=False)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('conversation_index', models.TextField(blank=True, null=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Array of email categories', size=None)),
                ('flag', models.JSONField(blank=True, default=dict, help_text='Follow-up flag status from Graph API', null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('web_link', models.URLField(blank=True, help_text='Outlook web link', null=True)),
                ('graph_metadata', models.JSONField(blank=True, default=dict, help_text='Additional Graph API fields stored as JSON')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Attachment metadata from Graph API (filename, content_type, size, etc.)')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether email has been processed by AI')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(help_text='Email account this email belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailaccount')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'email',
                'ordering': ['-date_received', '-created_at'],
                'indexes': [models.Index(fields=['email_account'], name='email_email_a_5cd171_idx'), models.Index(fields=['graph_id'], name='email_graph_i_018b6a_idx'), models.Index(fields=['internet_message_id'], name='email_interne_5fe058_idx'), models.Index(fields=['-date_received'], name='email_date_re_6a4252_idx'), models.Index(fields=['from_email'], name='email_from_em_a1af8a_idx'), models.Index(fields=['conversation_id'], name='email_convers_11920d_idx'), models.Index(fields=['is_processed'], name='email_is_proc_4f8408_idx'), models.Index(fields=['is_read'], name='email_is_read_d73262_idx')],
            },
        ),
    ]
