# Generated by Django 5.1.5 on 2026-02-10 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('responsibility', models.JSONField(blank=True, default=list, help_text='Array of profile UUIDs responsible for this contact')),
                ('phone', models.TextField(blank=True, null=True)),
                ('sector_coverage', models.JSONField(blank=True, default=list, help_text='Array of sector coverage areas')),
                ('rank', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, db_column='bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ['name', 'created_at'],
            },
        ),
    ]
