# Generated by Django 5.1.5 on 2026-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='source_count',
            field=models.IntegerField(default=0, help_text='Total deals sourced from this contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_handle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
