# Generated by Django 6.0.3 on 2026-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_linkedin_url_contact_source_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='follow_ups',
            field=models.TextField(blank=True, help_text='Legacy Follow Ups', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_meeting_date',
            field=models.TextField(blank=True, help_text='Legacy Last Meeting / Call Date (Stored as text)', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pipeline',
            field=models.TextField(blank=True, help_text='Legacy Pipeline/Status', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_coverage_person',
            field=models.TextField(blank=True, help_text='Person Covering - Primary', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ranking',
            field=models.TextField(blank=True, help_text='Legacy Ranking', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='secondary_coverage_person',
            field=models.TextField(blank=True, help_text='Person Covering - Secondary', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='total_deals_legacy',
            field=models.IntegerField(default=0, help_text='Total Deals from Legacy DB'),
        ),
    ]
