# Generated by Django 6.0.3 on 2026-07-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0030_aiauditlog_completed_at_aiauditlog_requested_by_and_more'),
        ('contacts', '0003_contact_follow_ups_contact_last_meeting_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceVerificationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_bank_name', models.TextField(blank=True, default='')),
                ('old_designation', models.TextField(blank=True, default='')),
                ('proposed_bank_name', models.TextField(blank=True, default='')),
                ('proposed_designation', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(max_length=1000)),
                ('source_title', models.TextField(blank=True, default='')),
                ('source_snippet', models.TextField(blank=True, default='')),
                ('source_domain', models.CharField(blank=True, default='', max_length=255)),
                ('search_query', models.TextField()),
                ('confidence', models.FloatField(default=0)),
                ('retrieved_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], db_index=True, default='PENDING', max_length=20)),
                ('accepted_fields', models.JSONField(blank=True, default=list)),
                ('reviewer_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_verifications', to='ai_orchestrator.aiauditlog')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_verifications', to='contacts.contact')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_workplace_verifications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workplace_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workplaceverificationsuggestion',
            index=models.Index(fields=['contact', 'status', '-created_at'], name='contacts_wo_contact_32d9fc_idx'),
        ),
    ]
