# Generated by Django 5.1.5 on 2026-01-29 17:49

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'bank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('pipeline', models.TextField(blank=True, null=True)),
                ('follow_ups', models.TextField(blank=True, null=True)),
                ('followup_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'meeting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('attachments', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Conflict', 'Conflict'), ('High', 'High')], db_column='status', default='Pending', max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('responsibility', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Array of profile UUIDs responsible for this contact', size=None)),
                ('phone', models.TextField(blank=True, null=True)),
                ('sector_coverage', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='Array of sector coverage areas', size=None)),
                ('rank', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, db_column='bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.bank')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='core.contact')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='core.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Contact',
                'verbose_name_plural': 'Meeting Contacts',
                'db_table': 'meeting_contact',
                'unique_together': {('meeting', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(related_name='meetings', through='core.MeetingContact', to='core.contact'),
        ),
        migrations.CreateModel(
            name='MeetingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_profiles', to='core.meeting')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_profiles', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Meeting Profile',
                'verbose_name_plural': 'Meeting Profiles',
                'db_table': 'meeting_profile',
                'unique_together': {('meeting', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='profiles',
            field=models.ManyToManyField(related_name='meetings', through='core.MeetingProfile', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(help_text='References the object ID (deal or contact)')),
                ('type', models.CharField(choices=[('deal', 'Deal'), ('contact', 'Contact')], help_text='Type of item (deal or contact)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict, help_text='Full JSON snapshot of the item')),
                ('search', models.TextField(blank=True, help_text='Searchable text (title/name)', null=True)),
                ('user_id', models.UUIDField(blank=True, help_text='User who made the change (from auth.uid())', null=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_id', 'type'], name='version_item_id_19037e_idx'), models.Index(fields=['-created_at'], name='version_created_94041c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('New', 'New'), ('To be Passed', 'To be Passed'), ('To Be Pass', 'To Be Pass'), ('Passed', 'Passed'), ('Portfolio', 'Portfolio'), ('Invested', 'Invested'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_column='priority', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_summary', models.TextField(blank=True, null=True)),
                ('funding_ask', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('deal_details', models.TextField(blank=True, null=True)),
                ('is_female_led', models.BooleanField(default=False)),
                ('management_meeting', models.BooleanField(default=False)),
                ('funding_ask_for', models.TextField(blank=True, null=True)),
                ('company_details', models.TextField(blank=True, null=True)),
                ('business_proposal_stage', models.BooleanField(default=False)),
                ('ic_stage', models.BooleanField(default=False)),
                ('responsibility', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Array of profile UUIDs responsible for this deal', size=None)),
                ('reasons_for_passing', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('other_contacts', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Array of contact UUIDs (not FK-enforced)', null=True, size=None)),
                ('fund', models.TextField(default='FUND3')),
                ('legacy_investment_bank', models.TextField(blank=True, null=True)),
                ('priority_rationale', models.TextField(blank=True, null=True)),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Array of theme tags', size=None)),
                ('bank', models.ForeignKey(blank=True, db_column='bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='core.bank')),
                ('primary_contact', models.ForeignKey(blank=True, db_column='primary_contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_deals', to='core.contact')),
                ('request', models.ForeignKey(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='core.request')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deal',
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['-created_at'], name='deal_created_1c7824_idx'), models.Index(fields=['priority'], name='deal_priorit_b10ace_idx'), models.Index(fields=['bank'], name='deal_bank_id_817ac5_idx')],
            },
        ),
    ]
