# Generated by Django 5.1.5 on 2026-02-10 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(help_text='References the object ID (deal or contact)')),
                ('type', models.CharField(choices=[('deal', 'Deal'), ('contact', 'Contact')], help_text='Type of item (deal or contact)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict, help_text='Full JSON snapshot of the item')),
                ('search', models.TextField(blank=True, help_text='Searchable text (title/name)', null=True)),
                ('user_id', models.UUIDField(blank=True, help_text='User who made the change (from auth.uid())', null=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_id', 'type'], name='version_item_id_19037e_idx'), models.Index(fields=['-created_at'], name='version_created_94041c_idx')],
            },
        ),
    ]
