# Generated by Django 5.1.5 on 2026-02-10 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_requests', '0001_initial'),
        ('banks', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('New', 'New'), ('To be Passed', 'To be Passed'), ('To Be Pass', 'To Be Pass'), ('Passed', 'Passed'), ('Portfolio', 'Portfolio'), ('Invested', 'Invested'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_column='priority', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_summary', models.TextField(blank=True, null=True)),
                ('funding_ask', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('deal_details', models.TextField(blank=True, null=True)),
                ('is_female_led', models.BooleanField(default=False)),
                ('management_meeting', models.BooleanField(default=False)),
                ('funding_ask_for', models.TextField(blank=True, null=True)),
                ('company_details', models.TextField(blank=True, null=True)),
                ('business_proposal_stage', models.BooleanField(default=False)),
                ('ic_stage', models.BooleanField(default=False)),
                ('responsibility', models.JSONField(blank=True, default=list, help_text='Array of profile UUIDs responsible for this deal')),
                ('reasons_for_passing', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('other_contacts', models.JSONField(blank=True, default=list, help_text='Array of contact UUIDs (not FK-enforced)', null=True)),
                ('fund', models.TextField(default='FUND3')),
                ('legacy_investment_bank', models.TextField(blank=True, null=True)),
                ('priority_rationale', models.TextField(blank=True, null=True)),
                ('themes', models.JSONField(blank=True, default=list, help_text='Array of theme tags')),
                ('bank', models.ForeignKey(blank=True, db_column='bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='banks.bank')),
                ('primary_contact', models.ForeignKey(blank=True, db_column='primary_contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_deals', to='contacts.contact')),
                ('request', models.ForeignKey(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='api_requests.request')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deal',
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['-created_at'], name='deal_created_1c7824_idx'), models.Index(fields=['priority'], name='deal_priorit_b10ace_idx'), models.Index(fields=['bank'], name='deal_bank_id_817ac5_idx')],
            },
        ),
    ]
