# Generated by Django 5.1.5 on 2026-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='responsibility',
        ),
        migrations.AddField(
            model_name='deal',
            name='responsibility',
            field=models.ManyToManyField(blank=True, help_text='Profiles responsible for this deal', related_name='deals', to='accounts.profile'),
        ),
    ]
