# Generated by Django 6.0.3 on 2026-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_responsibility_deal_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this deal data has been vectorized and stored in the vector database'),
        ),
    ]
