# Generated by Django 6.0.3 on 2026-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_is_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Combined text from linked source (Email/Files) for RAG context', null=True),
        ),
    ]
