# Generated by Django 6.0.3 on 2026-03-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ambiguities',
            field=models.JSONField(blank=True, default=list, help_text='List of ambiguous points identified during analysis'),
        ),
        migrations.AddField(
            model_name='deal',
            name='analysis_json',
            field=models.JSONField(blank=True, default=dict, help_text='Full raw JSON output from the AI analysis'),
        ),
        migrations.AddField(
            model_name='deal',
            name='thinking',
            field=models.TextField(blank=True, help_text='Internal reasoning process of the AI', null=True),
        ),
    ]
