# Generated by Django 6.0.3 on 2026-03-10 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('deals', '0005_deal_ambiguities_deal_analysis_json_deal_thinking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('document_type', models.CharField(choices=[('Pitch Deck', 'Pitch Deck'), ('Financials', 'Financials'), ('Legal', 'Legal'), ('Term Sheet', 'Term Sheet'), ('KYC', 'KYC'), ('Memo', 'Memo'), ('Other', 'Other')], default='Other', max_length=50)),
                ('onedrive_id', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.deal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'db_table': 'deal_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
