# Generated by Django 6.0.3 on 2026-03-10 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('deals', '0006_dealdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='current_phase',
            field=models.CharField(choices=[('Origination', 'Origination'), ('Screening', 'Screening'), ('Management Meeting', 'Management Meeting'), ('Due Diligence', 'Due Diligence'), ('IC Approval', 'IC Approval'), ('Term Sheet', 'Term Sheet'), ('Execution', 'Execution'), ('Portfolio', 'Portfolio'), ('Passed', 'Passed')], default='Origination', max_length=50),
        ),
        migrations.CreateModel(
            name='DealPhaseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_phase', models.CharField(choices=[('Origination', 'Origination'), ('Screening', 'Screening'), ('Management Meeting', 'Management Meeting'), ('Due Diligence', 'Due Diligence'), ('IC Approval', 'IC Approval'), ('Term Sheet', 'Term Sheet'), ('Execution', 'Execution'), ('Portfolio', 'Portfolio'), ('Passed', 'Passed')], max_length=50, null=True)),
                ('to_phase', models.CharField(choices=[('Origination', 'Origination'), ('Screening', 'Screening'), ('Management Meeting', 'Management Meeting'), ('Due Diligence', 'Due Diligence'), ('IC Approval', 'IC Approval'), ('Term Sheet', 'Term Sheet'), ('Execution', 'Execution'), ('Portfolio', 'Portfolio'), ('Passed', 'Passed')], max_length=50)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='deals.deal')),
            ],
            options={
                'db_table': 'deal_phase_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
