# Generated by Django 6.0.3 on 2026-03-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deal_current_phase_dealphaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing Background Files'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Status of background file processing from OneDrive', max_length=20),
        ),
    ]
