# Generated by Django 6.0.3 on 2026-03-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_deal_processing_error_deal_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='source_onedrive_id',
            field=models.CharField(blank=True, help_text='The OneDrive/SharePoint folder ID this deal was created from', max_length=255, null=True),
        ),
    ]
