# Generated by Django 6.0.3 on 2026-03-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_deal_source_onedrive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_flow_decisions',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary mapping stage IDs to decisions (e.g., {"1": "yes"})'),
        ),
        migrations.AddField(
            model_name='deal',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rejection_stage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_phase',
            field=models.CharField(choices=[('1: Deal Sourced', '1: Deal Sourced'), ('2: Initial Banker Call', '2: Initial Banker Call'), ('3: NDA Execution', '3: NDA Execution'), ('4: Initial Materials Review', '4: Initial Materials Review'), ('5: Financial Model Call', '5: Financial Model Call'), ('6: Additional Data Request', '6: Additional Data Request'), ('7: Industry Research', '7: Industry Research'), ('8: Reference Calls', '8: Reference Calls'), ('9: IA Model Build', '9: IA Model Build'), ('10: Field Visit', '10: Field Visit'), ('11: Business Proposal', '11: Business Proposal'), ('12: Term Sheet', '12: Term Sheet'), ('13: Full Due Diligence', '13: Full Due Diligence'), ('14: IC Note I', '14: IC Note I'), ('15: IC Feedback', '15: IC Feedback'), ('16: IC Note II', '16: IC Note II'), ('17: Definitive Documentation', '17: Definitive Documentation'), ('18: Closure', '18: Closure'), ('Passed', 'Passed'), ('Origination', 'Origination'), ('Screening', 'Screening'), ('Management Meeting', 'Management Meeting'), ('Due Diligence', 'Due Diligence'), ('IC Approval', 'IC Approval'), ('Term Sheet', 'Term Sheet'), ('Execution', 'Execution'), ('Portfolio', 'Portfolio')], default='1: Deal Sourced', max_length=50),
        ),
        migrations.AlterField(
            model_name='dealphaselog',
            name='from_phase',
            field=models.CharField(choices=[('1: Deal Sourced', '1: Deal Sourced'), ('2: Initial Banker Call', '2: Initial Banker Call'), ('3: NDA Execution', '3: NDA Execution'), ('4: Initial Materials Review', '4: Initial Materials Review'), ('5: Financial Model Call', '5: Financial Model Call'), ('6: Additional Data Request', '6: Additional Data Request'), ('7: Industry Research', '7: Industry Research'), ('8: Reference Calls', '8: Reference Calls'), ('9: IA Model Build', '9: IA Model Build'), ('10: Field Visit', '10: Field Visit'), ('11: Business Proposal', '11: Business Proposal'), ('12: Term Sheet', '12: Term Sheet'), ('13: Full Due Diligence', '13: Full Due Diligence'), ('14: IC Note I', '14: IC Note I'), ('15: IC Feedback', '15: IC Feedback'), ('16: IC Note II', '16: IC Note II'), ('17: Definitive Documentation', '17: Definitive Documentation'), ('18: Closure', '18: Closure'), ('Passed', 'Passed'), ('Origination', 'Origination'), ('Screening', 'Screening'), ('Management Meeting', 'Management Meeting'), ('Due Diligence', 'Due Diligence'), ('IC Approval', 'IC Approval'), ('Term Sheet', 'Term Sheet'), ('Execution', 'Execution'), ('Portfolio', 'Portfolio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealphaselog',
            name='to_phase',
            field=models.CharField(choices=[('1: Deal Sourced', '1: Deal Sourced'), ('2: Initial Banker Call', '2: Initial Banker Call'), ('3: NDA Execution', '3: NDA Execution'), ('4: Initial Materials Review', '4: Initial Materials Review'), ('5: Financial Model Call', '5: Financial Model Call'), ('6: Additional Data Request', '6: Additional Data Request'), ('7: Industry Research', '7: Industry Research'), ('8: Reference Calls', '8: Reference Calls'), ('9: IA Model Build', '9: IA Model Build'), ('10: Field Visit', '10: Field Visit'), ('11: Business Proposal', '11: Business Proposal'), ('12: Term Sheet', '12: Term Sheet'), ('13: Full Due Diligence', '13: Full Due Diligence'), ('14: IC Note I', '14: IC Note I'), ('15: IC Feedback', '15: IC Feedback'), ('16: IC Note II', '16: IC Note II'), ('17: Definitive Documentation', '17: Definitive Documentation'), ('18: Closure', '18: Closure'), ('Passed', 'Passed'), ('Origination', 'Origination'), ('Screening', 'Screening'), ('Management Meeting', 'Management Meeting'), ('Due Diligence', 'Due Diligence'), ('IC Approval', 'IC Approval'), ('Term Sheet', 'Term Sheet'), ('Execution', 'Execution'), ('Portfolio', 'Portfolio')], max_length=50),
        ),
    ]
