# Generated by Django 6.0.3 on 2026-03-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_deal_deal_flow_decisions_deal_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdocument',
            name='is_ai_analyzed',
            field=models.BooleanField(default=False, help_text='Whether this document was included in the AI summary generation'),
        ),
    ]
