# Generated by Django 6.0.3 on 2026-03-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_dealdocument_is_ai_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='analysis_history',
            field=models.JSONField(blank=True, default=list, help_text='Array of incremental analysis reports (v2, v3, etc.)'),
        ),
    ]
