# Generated by Django 6.0.3 on 2026-03-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_deal_analysis_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='source_drive_id',
            field=models.CharField(blank=True, help_text='The OneDrive/SharePoint Drive ID this deal belongs to', max_length=255, null=True),
        ),
    ]
