# Generated by Django 6.0.3 on 2026-03-20 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_deal_source_drive_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='ambiguities',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='analysis_history',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='analysis_json',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='thinking',
        ),
        migrations.CreateModel(
            name='DealAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('thinking', models.TextField(blank=True, help_text='Internal reasoning process of the AI', null=True)),
                ('ambiguities', models.JSONField(blank=True, default=list, help_text='List of ambiguous points identified during analysis')),
                ('analysis_json', models.JSONField(blank=True, default=dict, help_text='Full raw JSON output from the AI analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='deals.deal')),
            ],
            options={
                'db_table': 'deal_analysis',
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
