# Generated by Django 6.0.3 on 2026-04-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_dealanalysis_analysis_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='source_email_id',
            field=models.CharField(blank=True, help_text='The Microsoft Graph ID of the email this deal was created from', max_length=255, null=True),
        ),
    ]
