# Generated by Django 6.0.3 on 2026-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0024_folderanalysisdocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='folderanalysisdocument',
            new_name='deals_folde_audit_l_c1cd61_idx',
            old_name='deals_fold_audit_l_02e3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='folderanalysisdocument',
            new_name='deals_folde_audit_l_82b680_idx',
            old_name='deals_fold_audit_l_7a0f89_idx',
        ),
        migrations.RenameIndex(
            model_name='folderanalysisdocument',
            new_name='deals_folde_audit_l_173318_idx',
            old_name='deals_fold_audit_l_70d2de_idx',
        ),
        migrations.AlterField(
            model_name='dealdocument',
            name='extraction_mode',
            field=models.CharField(blank=True, choices=[('docproc_remote', 'Docproc Remote'), ('vllm_vision', 'vLLM Vision'), ('fallback_text', 'Fallback Text')], max_length=40, null=True),
        ),
    ]
