# Generated by Django 6.0.3 on 2026-04-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0025_rename_deals_fold_audit_l_02e3e4_idx_deals_folde_audit_l_c1cd61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='bank_name',
            field=models.TextField(blank=True, help_text='Raw bank name extracted from analysis', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='primary_contact_name',
            field=models.TextField(blank=True, help_text='Raw contact name extracted from analysis', null=True),
        ),
    ]
