# Generated by Django 6.0.3 on 2026-04-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0028_deal_analysis_prompt_dealgenerateddocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dealgenerateddocument',
            new_name='deal_genera_deal_id_5b1707_idx',
            old_name='deal_genera_deal_id_33da04_idx',
        ),
        migrations.RenameIndex(
            model_name='dealrelationshipcontext',
            new_name='deal_relati_deal_id_8f0e13_idx',
            old_name='deal_relati_deal_id_b024ed_idx',
        ),
        migrations.RenameIndex(
            model_name='dealrelationshipcontext',
            new_name='deal_relati_related_e80fc0_idx',
            old_name='deal_relati_related_853581_idx',
        ),
    ]
