# Generated by Django 6.0.3 on 2026-05-22 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0029_rename_deal_genera_deal_id_33da04_idx_deal_genera_deal_id_5b1707_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentureIntelligenceCompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, db_index=True, max_length=21, null=True, unique=True)),
                ('name', models.TextField()),
                ('registered_name', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('year_founded', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('total_funding', models.TextField(blank=True, null=True)),
                ('raw_profile_json', models.JSONField(blank=True, default=dict, help_text='Full raw JSON response from VI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VI Company Profile',
                'verbose_name_plural': 'VI Company Profiles',
                'db_table': 'vi_company_profile',
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceCompanyRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('target', 'Target Company'), ('competitor', 'Competitor Company')], default='target', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_relations', to='deals.ventureintelligencecompanyprofile')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vi_relations', to='deals.deal')),
            ],
            options={
                'verbose_name': 'VI Company Relation',
                'verbose_name_plural': 'VI Company Relations',
                'db_table': 'vi_company_relation',
                'unique_together': {('deal', 'company_profile')},
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceFinancialStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_type', models.CharField(choices=[('profit_loss', 'Profit & Loss'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow')], max_length=20)),
                ('fy', models.CharField(db_index=True, max_length=20)),
                ('fin_type', models.CharField(default='Standalone', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Structured row key-value data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_financial_statement',
                'ordering': ['-fy', 'statement_type'],
                'unique_together': {('company_profile', 'statement_type', 'fy', 'fin_type')},
            },
        ),
    ]
