# Generated by Django 6.0.3 on 2026-05-22 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0030_ventureintelligencecompanyprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='address_line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='auditor_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='company_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='contact_designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='contact_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='incorp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='is_xbrl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='listing_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='previous_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='shp_non_promoter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='shp_promoter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='shp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='telephone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='transacted_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VentureIntelligenceAngelInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('investors', models.JSONField(blank=True, default=list)),
                ('is_exited', models.BooleanField(blank=True, null=True)),
                ('is_agg_hide', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angel_investments', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_angel_investment',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceEpfoData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qrtr', models.TextField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epfo_data', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_epfo_data',
                'ordering': ['-qrtr'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceExecutive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('designation', models.TextField(blank=True, null=True)),
                ('belongs_to_firm_name', models.TextField(blank=True, null=True)),
                ('role_type', models.CharField(choices=[('management', 'Management'), ('board', 'Board')], default='management', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'verbose_name': 'VI Executive',
                'verbose_name_plural': 'VI Executives',
                'db_table': 'vi_executive',
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceIncubationInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('incubator', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubation_investments', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_incubation_investment',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceMergerAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('acquirer', models.TextField(blank=True, null=True)),
                ('company_valuation', models.TextField(blank=True, null=True)),
                ('company_valuation_post', models.TextField(blank=True, null=True)),
                ('revenue_multiple', models.TextField(blank=True, null=True)),
                ('revenue_multiple_post', models.TextField(blank=True, null=True)),
                ('is_hide_amount', models.BooleanField(blank=True, null=True)),
                ('is_asset_sale', models.BooleanField(blank=True, null=True)),
                ('is_minority_deal', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergers_acquisitions', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_merger_acquisition',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligencePEExit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_type', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('exit_investors', models.JSONField(blank=True, default=list)),
                ('amount', models.TextField(blank=True, null=True)),
                ('exit_status', models.TextField(blank=True, null=True)),
                ('valuation', models.TextField(blank=True, null=True)),
                ('revenue_multiple', models.TextField(blank=True, null=True)),
                ('is_vc', models.BooleanField(blank=True, null=True)),
                ('is_hide_amount', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_exits', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_pe_exit',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligencePEInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.TextField(blank=True, null=True)),
                ('deal_date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('amount_inr', models.TextField(blank=True, null=True)),
                ('investors', models.JSONField(blank=True, default=list)),
                ('exit_status', models.TextField(blank=True, null=True)),
                ('company_valuation_post_money', models.TextField(blank=True, null=True)),
                ('revenue_multiple_post_money', models.TextField(blank=True, null=True)),
                ('is_vc', models.TextField(blank=True, null=True)),
                ('is_amount_hide', models.BooleanField(blank=True, null=True)),
                ('is_debt_deal', models.BooleanField(blank=True, null=True)),
                ('is_agg_hide', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_investments', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_pe_investment',
                'ordering': ['-deal_date'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligencePEIPO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('ipo_investors', models.JSONField(blank=True, default=list)),
                ('ipo_size', models.TextField(blank=True, null=True)),
                ('is_investor_sale', models.BooleanField(blank=True, null=True)),
                ('ipo_valuation', models.TextField(blank=True, null=True)),
                ('is_amount_hide', models.BooleanField(blank=True, null=True)),
                ('is_vc', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_ipos', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_pe_ipo',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VentureIntelligenceSimilarCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sector', models.TextField(blank=True, null=True)),
                ('total_funding', models.TextField(blank=True, null=True)),
                ('latest_investment', models.JSONField(blank=True, default=dict)),
                ('city', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_companies', to='deals.ventureintelligencecompanyprofile')),
            ],
            options={
                'db_table': 'vi_similar_company',
                'ordering': ['name'],
            },
        ),
    ]
