# Generated by Django 6.0.3 on 2026-05-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0031_ventureintelligencecompanyprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventureintelligencecompanyprofile',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
