# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0032_ventureintelligencecompanyprofile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventureintelligencesimilarcompany',
            name='cin',
            field=models.CharField(blank=True, db_index=True, max_length=21, null=True),
        ),
    ]
