# Generated by Django 6.0.3 on 2026-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0033_ventureintelligencesimilarcompany_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='competitor_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Array of competitor candidate objects found by AI research', null=True),
        ),
    ]
