# Generated by Django 6.0.3 on 2026-07-28 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0037_dealcontradiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorResearchDiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('trigger', models.CharField(choices=[('AUTO_CREATE', 'Deal created'), ('AUTO_CONTEXT_CHANGE', 'Deal context changed'), ('MANUAL', 'Manual refresh')], default='MANUAL', max_length=30)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('audit_log_id', models.UUIDField(blank=True, null=True)),
                ('queries', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_discovery_runs', to='deals.deal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_research_discovery_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sector_research_discovery_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectorResearchRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.URLField(max_length=2000)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publisher_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('INDUSTRY_REPORT', 'Industry report'), ('ANNUAL_REPORT', 'Annual report'), ('STATUTORY_FILING', 'Statutory filing'), ('BROKERAGE_RESEARCH', 'Brokerage research'), ('OTHER_RESEARCH', 'Other research')], db_index=True, default='OTHER_RESEARCH', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('source_query', models.TextField(blank=True)),
                ('accessibility', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESTRICTED', 'Restricted'), ('UNAVAILABLE', 'Unavailable'), ('UNVERIFIED', 'Unverified')], db_index=True, default='UNVERIFIED', max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('preferred_source', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(default=0)),
                ('credibility_score', models.FloatField(default=0)),
                ('freshness_score', models.FloatField(default=0)),
                ('accessibility_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(db_index=True, default=0)),
                ('score_explanation', models.JSONField(blank=True, default=dict)),
                ('retrieved_at', models.DateTimeField()),
                ('last_verified_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_recommendations', to='deals.deal')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='deals.sectorresearchdiscoveryrun')),
            ],
            options={
                'db_table': 'sector_research_recommendation',
                'ordering': ['-total_score', '-publication_date', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='sectorresearchdiscoveryrun',
            index=models.Index(fields=['deal', '-created_at'], name='sector_rese_deal_id_87a15f_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorresearchdiscoveryrun',
            index=models.Index(fields=['deal', 'context_hash', 'status'], name='sector_rese_deal_id_771e76_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorresearchrecommendation',
            index=models.Index(fields=['deal', '-total_score'], name='sector_rese_deal_id_039c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorresearchrecommendation',
            index=models.Index(fields=['deal', 'document_type'], name='sector_rese_deal_id_f87806_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectorresearchrecommendation',
            constraint=models.UniqueConstraint(fields=('deal', 'canonical_url'), name='unique_research_recommendation_per_deal_url'),
        ),
    ]
