# Generated by Django 6.0.3 on 2026-08-13 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0038_sectorresearchdiscoveryrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DealPassReasonRemediationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_reason', models.TextField(blank=True, null=True)),
                ('new_reason', models.TextField()),
                ('deal_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_pass_reason_remediations', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_reason_remediation_audits', to='deals.deal')),
            ],
            options={
                'db_table': 'deal_pass_reason_remediation_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', '-created_at'], name='deal_pass_r_deal_id_a758c3_idx')],
            },
        ),
    ]
