# Generated by Django 6.0.3 on 2026-08-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_fund_classification_provenance(apps, schema_editor):
    Deal = apps.get_model('deals', 'Deal')
    Deal.objects.filter(fund__in=['FUND1', 'FUND2']).update(
        fund_classification_state='EXPLICIT',
        fund_classification_source_type='LEGACY_IMPORT',
        fund_classification_source_id=models.Case(
            models.When(fund='FUND1', then=models.Value('canonical-fund:FUND1')),
            default=models.Value('canonical-fund:FUND2'),
            output_field=models.CharField(),
        ),
    )
    Deal.objects.filter(fund='FUND3').update(
        fund_classification_state='DEFAULTED',
        fund_classification_source_type='SYSTEM_DEFAULT',
        fund_classification_source_id='default:FUND3',
    )


def reverse_fund_classification_provenance(apps, schema_editor):
    Deal = apps.get_model('deals', 'Deal')
    Deal.objects.update(
        fund_classification_state='DEFAULTED',
        fund_classification_source_type='SYSTEM_DEFAULT',
        fund_classification_source_id='default:FUND3',
        fund_classification_reviewed_by=None,
        fund_classification_reviewed_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('api_requests', '0001_initial'),
        ('banks', '0002_bank_description_bank_website_domain'),
        ('contacts', '0004_workplaceverificationsuggestion'),
        ('deals', '0039_deal_updated_at_dealpassreasonremediationaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='fund_classification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='fund_classification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deal_fund_classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='fund_classification_source_id',
            field=models.CharField(default='default:FUND3', max_length=500),
        ),
        migrations.AddField(
            model_name='deal',
            name='fund_classification_source_type',
            field=models.CharField(choices=[('WORKBOOK', 'Fund workbook'), ('ANALYST_REVIEW', 'Analyst review'), ('USER_INPUT', 'User input'), ('LEGACY_IMPORT', 'Legacy import'), ('SYSTEM_DEFAULT', 'System default')], default='SYSTEM_DEFAULT', max_length=30),
        ),
        migrations.AddField(
            model_name='deal',
            name='fund_classification_state',
            field=models.CharField(choices=[('EXPLICIT', 'Explicit'), ('DEFAULTED', 'Defaulted'), ('UNCERTAIN', 'Uncertain')], db_index=True, default='DEFAULTED', max_length=20),
        ),
        migrations.RunPython(
            backfill_fund_classification_provenance,
            reverse_fund_classification_provenance,
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('fund_classification_state__in', ['EXPLICIT', 'DEFAULTED', 'UNCERTAIN'])), name='deal_valid_fund_classification_state'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('fund_classification_state__in', ['DEFAULTED', 'UNCERTAIN']), models.Q(models.Q(('fund_classification_source_type', ''), _negated=True), models.Q(('fund_classification_source_id', ''), _negated=True)), models.Q(('fund_classification_reviewed_by__isnull', False), ('fund_classification_reviewed_at__isnull', False)), _connector='OR'), name='deal_explicit_fund_has_provenance'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fund_classification_reviewed_at__isnull', True), ('fund_classification_reviewed_by__isnull', True)), models.Q(('fund_classification_reviewed_at__isnull', False), ('fund_classification_reviewed_by__isnull', False)), _connector='OR'), name='deal_fund_reviewer_fields_paired'),
        ),
    ]
