# Generated by Django 6.0.3 on 2026-08-13 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0040_deal_fund_classification_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealReceiptDateSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_date', models.DateField()),
                ('source_type', models.CharField(choices=[('WORKBOOK', 'Approved workbook'), ('SOURCE_EMAIL', 'Linked source email'), ('ANALYST', 'Analyst evidence')], max_length=20)),
                ('source_id', models.CharField(max_length=1000)),
                ('evidence', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('CONFLICT', 'Conflicting evidence'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_date_suggestions', to='deals.deal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipt_date_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deal_receipt_date_suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealReceiptDateAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField()),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=1000)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_date_audits', to='deals.deal')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_receipt_date_audits', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_audits', to='deals.dealreceiptdatesuggestion')),
            ],
            options={
                'db_table': 'deal_receipt_date_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealreceiptdatesuggestion',
            index=models.Index(fields=['deal', 'status'], name='deal_receip_deal_id_cd5c24_idx'),
        ),
        migrations.AddIndex(
            model_name='dealreceiptdatesuggestion',
            index=models.Index(fields=['status', 'proposed_date'], name='deal_receip_status_077b82_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealreceiptdatesuggestion',
            constraint=models.UniqueConstraint(fields=('deal', 'proposed_date', 'source_type', 'source_id'), name='unique_deal_receipt_date_source_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='dealreceiptdatesuggestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='receipt_suggestion_reviewer_fields_paired'),
        ),
        migrations.AddIndex(
            model_name='dealreceiptdateaudit',
            index=models.Index(fields=['deal', '-created_at'], name='deal_receip_deal_id_cf7564_idx'),
        ),
    ]
