# Generated by Django 6.0.3 on 2026-08-13 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0030_aiauditlog_completed_at_aiauditlog_requested_by_and_more'),
        ('deals', '0041_dealreceiptdatesuggestion_dealreceiptdateaudit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorResearchAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('DOWNLOADING', 'Downloading'), ('ATTACHED', 'Attached'), ('EXTRACTING', 'Extracting'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('source_url', models.URLField(max_length=2000)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('content_length', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('access_evidence', models.JSONField(blank=True, default=dict)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_research_acquisitions', to=settings.AUTH_USER_MODEL)),
                ('audit_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_acquisitions', to='ai_orchestrator.aiauditlog')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_acquisitions', to='deals.deal')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_acquisition', to='deals.dealdocument')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acquisition', to='deals.sectorresearchrecommendation')),
            ],
            options={
                'db_table': 'sector_research_acquisition',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', 'status'], name='sector_rese_deal_id_e557b6_idx')],
            },
        ),
    ]
