# Generated by Django 6.0.3 on 2026-08-30 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0048_limit_onedrive_provenance_to_deal_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorResearchSourceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_preferred', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('query_templates', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sector_research_source_rule',
                'ordering': ['name', 'domain'],
            },
        ),
    ]
