# Generated by Django 5.1.5 on 2026-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='website_domain',
            field=models.TextField(blank=True, help_text='Primary domain (e.g., avendus.com) for deduplication', null=True),
        ),
    ]
