# Generated by Django 6.0.3 on 2026-08-13 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('deals', '0042_sectorresearchacquisition'),
        ('work_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id_snapshot', models.UUIDField(db_index=True)),
                ('task_title', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('assigned', 'Assigned'), ('prioritized', 'Prioritized'), ('due_date_changed', 'Due date changed'), ('deleted', 'Deleted'), ('suggestion_accepted', 'Suggestion accepted')], db_index=True, max_length=30)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to='accounts.profile')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='deals.deal')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='work_items.task')),
            ],
            options={
                'db_table': 'task_activity',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['deal', '-created_at'], name='task_activity_deal_time_idx'), models.Index(fields=['task_id_snapshot', '-created_at'], name='task_activity_task_time_idx')],
            },
        ),
    ]
