# Generated by Django 5.1.5 on 2026-01-29 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to Django User (optional, for compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
                'ordering': ['name', 'email'],
                'indexes': [models.Index(fields=['email'], name='profile_email_ffc546_idx'), models.Index(fields=['is_admin'], name='profile_is_admi_12c629_idx')],
            },
        ),
    ]
