# Generated by Django 5.1.5 on 2026-02-10 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('pipeline', models.TextField(blank=True, null=True)),
                ('follow_ups', models.TextField(blank=True, null=True)),
                ('followup_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'meeting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='contacts.contact')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Contact',
                'verbose_name_plural': 'Meeting Contacts',
                'db_table': 'meeting_contact',
                'unique_together': {('meeting', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingContact', to='contacts.contact'),
        ),
        migrations.CreateModel(
            name='MeetingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_profiles', to='meetings.meeting')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_profiles', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Meeting Profile',
                'verbose_name_plural': 'Meeting Profiles',
                'db_table': 'meeting_profile',
                'unique_together': {('meeting', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='profiles',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingProfile', to='accounts.profile'),
        ),
    ]
