# Generated by Django 5.1.5 on 2026-06-15 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('deals', '0033_ventureintelligencesimilarcompany_cin'),
        ('meetings', '0001_initial'),
        ('microsoft', '0008_alter_email_conversation_id_alter_email_graph_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(help_text='Raw meeting note text from manual entry or email ingestion')),
                ('summary', models.TextField(blank=True, default='')),
                ('meeting_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('attendees', models.TextField(blank=True, default='', help_text='Free-form attendee list captured from notes or email')),
                ('action_items', models.TextField(blank=True, default='')),
                ('decisions', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('email', 'Email')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_indexed', models.BooleanField(default=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embedding_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_notes', to='accounts.profile')),
                ('deals', models.ManyToManyField(blank=True, help_text='Deals discussed in this meeting note', related_name='meeting_notes', to='deals.deal')),
                ('source_email', models.ForeignKey(blank=True, help_text='Email this meeting note was ingested from, when applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='microsoft.email')),
            ],
            options={
                'verbose_name': 'Meeting Note',
                'verbose_name_plural': 'Meeting Notes',
                'db_table': 'meeting_note',
                'ordering': ['-meeting_at', '-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='meeting_not_source_4dfd45_idx'), models.Index(fields=['meeting_at'], name='meeting_not_meeting_f267f7_idx'), models.Index(fields=['is_indexed'], name='meeting_not_is_inde_0af1b6_idx')],
            },
        ),
    ]
