# Generated by Django 6.0.3 on 2026-08-13 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0030_aiauditlog_completed_at_aiauditlog_requested_by_and_more'),
        ('deals', '0041_dealreceiptdatesuggestion_dealreceiptdateaudit_and_more'),
        ('meetings', '0002_meetingnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSignalFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('RED', 'Red flag'), ('GREEN', 'Green signal'), ('QUESTION', 'Open question')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('confidence', models.CharField(default='medium', max_length=20)),
                ('evidence', models.JSONField(default=list)),
                ('source_note_ids', models.JSONField(default=list)),
                ('detection_count', models.PositiveIntegerField(default=1)),
                ('review_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], db_index=True, default='UNREVIEWED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_signal_flags', to='deals.deal')),
                ('first_audit_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_detected_meeting_signals', to='ai_orchestrator.aiauditlog')),
                ('latest_audit_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_detected_meeting_signals', to='ai_orchestrator.aiauditlog')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meeting_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_signal_flag',
                'ordering': ['-last_detected_at', 'kind', 'title'],
                'indexes': [models.Index(fields=['deal', 'review_status'], name='meeting_sig_deal_id_204516_idx'), models.Index(fields=['deal', 'kind'], name='meeting_sig_deal_id_fc9193_idx')],
                'constraints': [models.UniqueConstraint(fields=('deal', 'fingerprint'), name='unique_meeting_signal_fingerprint_per_deal'), models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewer__isnull', True)), models.Q(('reviewed_at__isnull', False), ('reviewer__isnull', False)), _connector='OR'), name='meeting_signal_reviewer_fields_paired')],
            },
        ),
    ]
