# Generated by Django 5.1.5 on 2026-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Status of the background AI processing task', max_length=20),
        ),
    ]
