# Generated by Django 5.1.5 on 2026-02-25 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_email', models.EmailField(help_text='The email address this token is for (e.g. dms-demo@india-alt.com)', max_length=254, unique=True)),
                ('token_type', models.CharField(choices=[('application', 'Application'), ('delegated', 'Delegated')], default='application', max_length=20)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('token_cache', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Microsoft Token',
                'verbose_name_plural': 'Microsoft Tokens',
                'db_table': 'microsoft_token',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Status of the background AI processing task', max_length=20),
        ),
    ]
