# Generated by Django 5.1.5 on 2026-02-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_responsibility_deal_responsibility'),
        ('microsoft', '0002_email_processing_error_email_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='The deal this email is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='email',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Full cleaned text from body and attachments for AI chat context', null=True),
        ),
    ]
