# Generated by Django 5.1.5 on 2026-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0002_microsofttoken_email_processing_error_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsofttoken',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Microsoft Token', 'verbose_name_plural': 'Microsoft Tokens'},
        ),
        migrations.AddIndex(
            model_name='microsofttoken',
            index=models.Index(fields=['account_email'], name='microsoft_t_account_ca22d8_idx'),
        ),
        migrations.AddIndex(
            model_name='microsofttoken',
            index=models.Index(fields=['token_type'], name='microsoft_t_token_t_046e64_idx'),
        ),
    ]
