# Generated by Django 6.0.3 on 2026-03-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_is_indexed'),
        ('microsoft', '0003_alter_microsofttoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='The deal this email is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='email',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Full cleaned text from body and attachments for AI chat context', null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this email and its attachments have been vectorized'),
        ),
    ]
