# Generated by Django 6.0.3 on 2026-03-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0005_email_analysis_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='conversation_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='graph_id',
            field=models.TextField(db_index=True, help_text='Microsoft Graph API message ID', unique=True),
        ),
    ]
