# Generated by Django 6.0.3 on 2026-03-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0006_alter_email_conversation_id_alter_email_graph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='web_link',
            field=models.URLField(blank=True, help_text='Outlook web link', max_length=1000, null=True),
        ),
    ]
