# Generated by Django 6.0.3 on 2026-03-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0007_alter_email_web_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='graph_id',
            field=models.CharField(db_index=True, help_text='Microsoft Graph API message ID', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='internet_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Internet Message ID (unique email identifier)', max_length=1000, null=True),
        ),
    ]
