# Generated by Django 5.2.17 on 2026-09-07 04:25

import django.db.models.deletion
import microsoft.ingestion_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0049_sectorresearchsourcerule'),
        ('meetings', '0004_meetingnote_contacts'),
        ('microsoft', '0009_email_html_sanitizer_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsoft.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailIngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_version', models.CharField(max_length=64)),
                ('pipeline_version', models.PositiveIntegerField(default=1)),
                ('source', models.JSONField(default=dict)),
                ('classification', models.JSONField(default=dict)),
                ('match', models.JSONField(default=dict)),
                ('stages', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('decision_log', models.JSONField(default=list)),
                ('status', models.CharField(db_index=True, default='pending', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='microsoft.email')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailPrivateBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
                ('file', models.FileField(max_length=500, storage=microsoft.ingestion_models.PrivateEmailStorage(), upload_to='attachments')),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsoft.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=24)),
                ('provenance', models.JSONField(default=dict)),
                ('index_status', models.CharField(default='pending', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_evidence_links', to='deals.dealdocument')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsoft.emailaccount')),
                ('meeting_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_evidence_links', to='meetings.meetingnote')),
                ('blob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsoft.emailprivateblob')),
            ],
        ),
        migrations.CreateModel(
            name='EmailContributionOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=1100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsoft.emailcontribution')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='microsoft.emailevidencelink')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='microsoft.emailingestionrun')),
                ('blob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsoft.emailprivateblob')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailcontribution',
            constraint=models.UniqueConstraint(fields=('email_account', 'fingerprint'), name='email_contribution_unique'),
        ),
        migrations.AddConstraint(
            model_name='emailingestionrun',
            constraint=models.UniqueConstraint(fields=('email', 'input_version', 'pipeline_version'), name='email_ingestion_input_unique'),
        ),
        migrations.AddConstraint(
            model_name='emailprivateblob',
            constraint=models.UniqueConstraint(fields=('email_account', 'sha256'), name='email_blob_unique'),
        ),
        migrations.AddConstraint(
            model_name='emailevidencelink',
            constraint=models.UniqueConstraint(fields=('email_account', 'deal', 'source_key', 'kind'), name='email_evidence_output_unique'),
        ),
        migrations.AddConstraint(
            model_name='emailcontributionoccurrence',
            constraint=models.UniqueConstraint(fields=('run', 'source_key'), name='email_occurrence_unique'),
        ),
    ]
