# Generated by Django 6.0.3 on 2026-08-30 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_email_alter_profile_user'),
        ('deals', '0048_limit_onedrive_provenance_to_deal_identity'),
        ('meetings', '0004_meetingnote_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IATheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('feed_url', models.URLField(blank=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('requires_licensed_api', models.BooleanField(default=False)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REPORT', 'Industry report'), ('TRANSCRIPT', 'Industry call transcript')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=255)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'All IA users'), ('RESTRICTED', 'Publisher and administrators')], default='INTERNAL', max_length=20)),
                ('confidentiality', models.CharField(blank=True, max_length=255)),
                ('redaction_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_publication', to='deals.dealdocument')),
                ('meeting_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_publication', to='meetings.meetingnote')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_knowledge_documents', to='accounts.profile')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'sector'], name='industry_kn_kind_953445_idx'), models.Index(fields=['visibility', '-created_at'], name='industry_kn_visibil_88d8aa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deal_document__isnull', False), ('meeting_note__isnull', True)), models.Q(('deal_document__isnull', True), ('meeting_note__isnull', False)), _connector='OR'), name='knowledge_document_has_one_source')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('companies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dismissed_by', models.ManyToManyField(blank=True, related_name='dismissed_industry_news', to=settings.AUTH_USER_MODEL)),
                ('linked_deals', models.ManyToManyField(blank=True, related_name='industry_news', to='deals.deal')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_industry_news', to=settings.AUTH_USER_MODEL)),
                ('themes', models.ManyToManyField(blank=True, related_name='articles', to='industry_knowledge.iatheme')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='industry_knowledge.newssource')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='industry_kn_source__97e6f8_idx')],
            },
        ),
    ]
