# Generated by Django 6.0.3 on 2026-08-30 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_knowledge', '0002_seed_news_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iatheme',
            name='subscribed_by',
            field=models.ManyToManyField(blank=True, related_name='industry_theme_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='participants',
            field=models.TextField(blank=True),
        ),
    ]
