# Generated by Django 5.2.17 on 2026-09-05 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0049_sectorresearchsourcerule'),
        ('industry_knowledge', '0003_iatheme_subscribed_by_knowledgedocument_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('overview', models.TextField(blank=True, default='', help_text='Industry overview and sector dynamics')),
                ('context', models.TextField(blank=True, default='', help_text='Analyst notes, thesis, and investment context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='industry_documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('document_type', models.CharField(default='Industry Report', max_length=100)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_attachments', to='deals.dealdocument')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='industry_knowledge.industry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryNewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600)),
                ('url', models.URLField(max_length=1000)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='industry_knowledge.industry')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('industry', 'url'), name='unique_industry_news_url')],
            },
        ),
    ]
