# Generated by Django 5.2.17 on 2026-09-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_knowledge', '0005_industry_taxonomy_and_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='last_summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='summary_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='industry',
            name='summary_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='industry',
            name='summary_status',
            field=models.CharField(choices=[('IDLE', 'Ready'), ('QUEUED', 'Queued'), ('RUNNING', 'Searching'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
    ]
