# Generated by Django 5.2.17 on 2026-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_knowledge', '0006_industry_last_summarized_at_industry_summary_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='preferred_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='industry',
            name='research_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
