# Generated by Django 5.1.5 on 2026-02-20 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPersonality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for this personality', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this personality is for')),
                ('system_instructions', models.TextField(help_text="The core 'system' prompt that defines behavior")),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default personality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Personality',
                'verbose_name_plural': 'AI Personalities',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AISkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for this skill (e.g., deal_extraction)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_template', models.TextField(help_text='The task-specific prompt template')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='Expected JSON structure for input (optional)')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='Expected JSON structure for output (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Skill',
                'verbose_name_plural': 'AI Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(default='email', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.CharField(max_length=100)),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('raw_response', models.TextField()),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('request_duration_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_orchestrator.aipersonality')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_orchestrator.aiskill')),
            ],
            options={
                'verbose_name': 'AI Audit Log',
                'verbose_name_plural': 'AI Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='ai_orchestr_source__cce83b_idx'), models.Index(fields=['-created_at'], name='ai_orchestr_created_ed48b6_idx')],
            },
        ),
    ]
