# Generated by Django 5.1.5 on 2026-02-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='model_provider',
            field=models.CharField(default='ollama', max_length=50),
        ),
        migrations.AddField(
            model_name='aipersonality',
            name='model_provider',
            field=models.CharField(choices=[('ollama', 'Ollama (Local/Azure)'), ('openai', 'OpenAI (GPT-4o)'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], default='ollama', max_length=50),
        ),
        migrations.AddField(
            model_name='aipersonality',
            name='text_model_name',
            field=models.CharField(default='llama3.1:latest', help_text='Model for text-only tasks', max_length=100),
        ),
        migrations.AddField(
            model_name='aipersonality',
            name='vision_model_name',
            field=models.CharField(default='llava:latest', help_text='Model for tasks with images/charts', max_length=100),
        ),
    ]
