# Generated by Django 6.0.3 on 2026-03-04 07:50

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    """Create the vector extension if it doesn't exist."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0002_aiauditlog_model_provider_and_more'),
        ('deals', '0003_deal_is_indexed'),
    ]

    operations = [
        migrations.RunPython(
            create_vector_extension,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('email', 'Email Body'), ('attachment', 'Email Attachment'), ('onedrive', 'OneDrive File'), ('deal_summary', 'Deal Summary')], max_length=50)),
                ('source_id', models.CharField(help_text='Original ID of the source (Email ID, File ID, etc.)', max_length=255)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(help_text='The deal this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'indexes': [models.Index(fields=['deal', 'source_type'], name='ai_orchestr_deal_id_be209e_idx')],
            },
        ),
    ]
