# Generated by Django 6.0.3 on 2026-03-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0004_aiconversation_aimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='thinking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
