# Generated by Django 6.0.3 on 2026-03-05 06:50

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0005_aimessage_thinking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='source_type',
            field=models.CharField(choices=[('email', 'Email Body'), ('attachment', 'Email Attachment'), ('onedrive', 'OneDrive File'), ('deal_summary', 'Deal Summary'), ('ai_thinking', 'AI Reasoning Logic'), ('ai_ambiguities', 'AI Identified Ambiguities'), ('extracted_source', 'Raw Extracted Text')], max_length=50),
        ),
    ]
