# Generated by Django 6.0.3 on 2026-03-10 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0006_alter_documentchunk_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('directives', models.JSONField(default=list, help_text="List of rules: ['Find all forensic risks', 'Convert units to INR']")),
                ('output_schema', models.JSONField(default=dict, help_text='Mandatory JSON structure for the AI response')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Protocol',
                'verbose_name_plural': 'Analysis Protocols',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='source_type',
            field=models.CharField(choices=[('email', 'Email Body'), ('attachment', 'Email Attachment'), ('onedrive', 'OneDrive File'), ('deal_summary', 'Deal Summary')], max_length=50),
        ),
    ]
