# Generated by Django 6.0.3 on 2026-03-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0008_alter_documentchunk_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
