# Generated by Django 6.0.3 on 2026-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0009_aiauditlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='source_metadata',
            field=models.JSONField(blank=True, help_text='Extra context like file trees or drive IDs', null=True),
        ),
    ]
