# Generated by Django 6.0.3 on 2026-03-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0010_aiauditlog_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiauditlog',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, null=True),
        ),
    ]
