# Generated by Django 6.0.3 on 2026-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0011_alter_aiauditlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of the associated Celery task', max_length=255, null=True),
        ),
    ]
