# Generated by Django 6.0.3 on 2026-03-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0012_aiauditlog_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='raw_thinking',
            field=models.TextField(blank=True, help_text='Real-time thinking trace', null=True),
        ),
    ]
