# Generated by Django 6.0.3 on 2026-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0013_aiauditlog_raw_thinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='context_label',
            field=models.CharField(blank=True, help_text='Descriptive label (Folder Name, Email Subject, etc.)', max_length=500, null=True),
        ),
    ]
