# Generated by Django 6.0.3 on 2026-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0015_aiflowdefinition_aiflowversion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiflowversion',
            new_name='ai_orchestr_flow_id_b6b5e9_idx',
            old_name='ai_orchestr_flow_id_e2f9b2_idx',
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='worker_logs',
            field=models.JSONField(blank=True, default=list, help_text='Execution logs from celery workers'),
        ),
    ]
