# Generated by Django 6.0.3 on 2026-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0021_expand_embedding_vectors_to_1024'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dealretrievalprofile',
            new_name='ai_orchestr_deal_id_1a26c2_idx',
            old_name='ai_orchestr_deal_id_77216e_idx',
        ),
        migrations.RenameIndex(
            model_name='dealretrievalprofile',
            new_name='ai_orchestr_embeddi_0041fa_idx',
            old_name='ai_orchestr_embeddi_c5f7cc_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='ai_orchestr_audit_l_b8bcea_idx',
            old_name='ai_orchestr_audit_l_53a486_idx',
        ),
        migrations.AlterField(
            model_name='aiauditlog',
            name='model_provider',
            field=models.CharField(default='vllm', max_length=50),
        ),
        migrations.AlterField(
            model_name='aipersonality',
            name='model_provider',
            field=models.CharField(choices=[('vllm', 'vLLM (OpenAI-Compatible)')], default='vllm', max_length=50),
        ),
        migrations.AlterField(
            model_name='aipersonality',
            name='text_model_name',
            field=models.CharField(default='default', help_text='Model for text-only tasks', max_length=200),
        ),
        migrations.AlterField(
            model_name='aipersonality',
            name='vision_model_name',
            field=models.CharField(default='default', help_text='Model for tasks with images/charts', max_length=200),
        ),
    ]
