# Generated by Django 6.0.3 on 2026-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0022_rename_ai_orchestr_deal_id_77216e_idx_ai_orchestr_deal_id_1a26c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiskill',
            name='system_template',
            field=models.TextField(blank=True, help_text='Optional system-level instructions for this skill'),
        ),
    ]
