# Generated by Django 6.0.3 on 2026-05-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0025_backfill_deal_chat_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipersonality',
            name='model_provider',
            field=models.CharField(choices=[('vllm', 'vLLM (OpenAI-Compatible)'), ('anthropic', 'Anthropic Claude API')], default='vllm', max_length=50),
        ),
    ]
