# Generated by Django 6.0.3 on 2026-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0026_alter_aipersonality_model_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key (e.g. CLAUDE_TEXT_MODEL)', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this setting is for', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI System Setting',
                'verbose_name_plural': 'AI System Settings',
                'ordering': ['key'],
            },
        ),
    ]
