# Generated by Django 5.1.5 on 2026-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0027_aisystemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='source_type',
            field=models.CharField(choices=[('email', 'Email Body'), ('attachment', 'Email Attachment'), ('onedrive', 'OneDrive File'), ('deal_summary', 'Deal Summary'), ('document', 'Deal Document Artifact'), ('analysis_document', 'Folder Analysis Document Artifact'), ('meeting_note', 'Meeting Note'), ('ai_thinking', 'AI Reasoning Logic'), ('ai_ambiguities', 'AI Identified Ambiguities'), ('extracted_source', 'Raw Extracted Text')], max_length=50),
        ),
    ]
