# Generated by Django 6.0.3 on 2026-07-27 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0029_hybrid_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='skill_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='is_industry_overview_eligible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ai_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='skill_format',
            field=models.CharField(choices=[('native_prompt_v1', 'Native prompt template v1'), ('claude_prompt_v1', 'Claude prompt-only subset v1')], default='native_prompt_v1', max_length=30),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('retired', 'Retired')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
