# Generated by Django 6.0.3 on 2026-08-13 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0030_aiauditlog_completed_at_aiauditlog_requested_by_and_more'),
        ('deals', '0042_sectorresearchacquisition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealIndustrySkillAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_run', models.BooleanField(default=False)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('source_document_ids', models.JSONField(blank=True, default=list)),
                ('last_context_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_run_status', models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20)),
                ('last_run_trigger', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['skill__name'],
            },
        ),
        migrations.AddField(
            model_name='dealindustryskillassignment',
            name='configured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_industry_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealindustryskillassignment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_skill_assignments', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealindustryskillassignment',
            name='last_audit_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_skill_assignments', to='ai_orchestrator.aiauditlog'),
        ),
        migrations.AddField(
            model_name='dealindustryskillassignment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_assignments', to='ai_orchestrator.aiskill'),
        ),
        migrations.AddIndex(
            model_name='dealindustryskillassignment',
            index=models.Index(fields=['deal', 'enabled', 'auto_run'], name='ai_orchestr_deal_id_7a792f_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealindustryskillassignment',
            constraint=models.UniqueConstraint(fields=('deal', 'skill'), name='unique_deal_industry_skill_assignment'),
        ),
    ]
