# Generated by Django 6.0.3 on 2026-08-16 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0031_dealindustryskillassignment_and_more'),
        ('deals', '0042_sectorresearchacquisition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPipelineDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIPipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('prompt', 'Prompt'), ('skill', 'Skill')], max_length=20)),
                ('required_variables', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pipeline__name', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_guardrail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('system_template', models.TextField(blank=True, default='')),
                ('user_template', models.TextField(blank=True, default='')),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='AISkillRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('system_template', models.TextField(blank=True, default='')),
                ('prompt_template', models.TextField(blank=True, default='')),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('skill_format', models.CharField(choices=[('native_prompt_v1', 'Native prompt template v1'), ('claude_prompt_v1', 'Claude prompt-only subset v1')], default='native_prompt_v1', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ai_orchestrator.aipipelinedefinition'),
        ),
        migrations.AddField(
            model_name='aipipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ai_orchestrator.aipipelinedefinition'),
        ),
        migrations.AddField(
            model_name='aipipelinestage',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_stages', to='ai_orchestrator.aiskill'),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ai_orchestrator.aipipelinestage'),
        ),
        migrations.AddField(
            model_name='aipipelinestage',
            name='prompt_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='ai_orchestrator.aipromptdefinition'),
        ),
        migrations.AddField(
            model_name='aipromptrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_prompt_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipromptrevision',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ai_orchestrator.aipromptdefinition'),
        ),
        migrations.AddField(
            model_name='aipromptrevision',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ai_prompt_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='prompt_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ai_orchestrator.aipromptrevision'),
        ),
        migrations.AddField(
            model_name='aiskillrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_skill_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiskillrevision',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ai_skill_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiskillrevision',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ai_orchestrator.aiskill'),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='skill_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ai_orchestrator.aiskillrevision'),
        ),
        migrations.AddConstraint(
            model_name='aipipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'key'), name='unique_ai_pipeline_stage_key'),
        ),
        migrations.AddConstraint(
            model_name='aipromptrevision',
            constraint=models.UniqueConstraint(fields=('definition', 'revision'), name='unique_ai_prompt_revision'),
        ),
        migrations.AddConstraint(
            model_name='aiskillrevision',
            constraint=models.UniqueConstraint(fields=('skill', 'revision'), name='unique_ai_skill_revision'),
        ),
    ]
