# Generated by Django 6.0.3 on 2026-08-26 02:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0034_vmcontroloperation'),
        ('deals', '0043_multimodal_document_extraction_mode'),
    ]

    operations = [
        # Migration 0029 created these columns with idempotent SQL, but did not
        # add them to Django's migration state. Register the model fields here
        # without trying to create the existing database columns again.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='documentchunk',
                    name='search_text',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='documentchunk',
                    name='search_vector',
                    field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
            ],
        ),
        # HNSW builds are intentionally deferred. Railway's deploy container has
        # a small /dev/shm budget, and building these indexes during startup can
        # make the healthcheck time out. The indexes remain in migration state;
        # run `build_vector_indexes` after deploy to create them concurrently.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='dealretrievalprofile',
                    index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='dealprofile_embedding_hnsw', opclasses=['vector_cosine_ops']),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='docchunk_search_vector_gin'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='documentchunk',
                    index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='docchunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
                ),
            ],
        ),
    ]
